### ISSUE TITLE
Unexpected close behavior

### ISSUE THREAD

**Issue by stephantabor** [vue-comps/vue-side-nav#3]
If the screen width is small enough, the `drag-handle` will overlap with the nav as seen below. Clicking the area of the nav that is overlapped by the `drag-handle` will close the nav, even when `close-on-click` is `false`
- ![](https://puu.sh/qGYRb/bfd92c0efd.png)

If the window is wide enough this doesn't happen
- ![](https://puu.sh/qGZ0h/2322f3aef7.png)

**Comment by paulpflug** [comment]
thanks for reporting :+1: 
I changed to `width:100%` but `z-index` smaller than the nav
works as expected in `v1.0.0`
