### ISSUE TITLE
side bar won't open based on props

### ISSUE THREAD

**Issue by jcdavison** [vue-comps/vue-side-nav#4]
Given the below code, 

```
<template>
  <div>
    <div>
      <side-nav v-bind:is-opened.sync=truthyValue v-bind:close-on-click.sync=otherTruthyValue></side-nav>
    </div>
  </div>
</template>
<script>

  const sideNavItems = [
    { name: 'Accounts', componentClass: 'link--primary', href: '/accounts' }
  ];

  import sideNavItem from 'components/sideNavItem.vue'

  export default {
    data: function() {
      return {
        sideNavItems: sideNavItems,
        otherTruthyValue: true,
        truthyValue: true,
        someDatum: 'fooWaffles'
      }
    },
    beforeCompile: function() {
    },
    props: ['is-opened'],
    created: function () {
    },
    ready: function () {
    },
    components: {
      "side-nav": require("vue-side-nav"),
      "icon": require("vue-icons"),
      sideNavItem
    },
    methods: {
      toggle: function() {
      },
    },
  }
</script>
```

I would expect that the component `Side-Nav` would be paying attention to `truthyValue` which is in this case `true`, notice the screenshot.

![screenshot 2016-10-05 17 03 30](https://cloud.githubusercontent.com/assets/6944945/19136048/1d59bda8-8b1e-11e6-97af-da1f63817f58.png)

Also notice that if we instantiate the component with `right`

```
      <side-nav right v-bind:is-opened.sync=truthyValue v-bind:close-on-click.sync=otherTruthyValue></side-nav>
```

The side-bar shows up, but the attributes look all messed up and the sidebar is still on the left

![screenshot 2016-10-05 17 08 30](https://cloud.githubusercontent.com/assets/6944945/19136089/79e8840a-8b1e-11e6-9483-c69c1be36081.png)

Admittedly, I am pretty new to Vue.js but very experienced with React and child/parent stuff, not that I think anything related to state/reactivity actually matters here.

Any insight into what I might do to get the side-nav to show properly would be much appreciated.  Also, we are using vue 1.x (which version of vue is needed to make this library work is unclear to me)

**Comment by paulpflug** [comment]
Very strange. Both cases work for me. It needs vue 1.x - so this should be ok. Do you get any errors?

It uses [vue-mixins/isOpened](https://github.com/paulpflug/vue-mixins/blob/master/src/isOpened.coffee#L22) for opened state mangement, which depends on `ready` lifecycle event of `vue`.
This will never be emitted, if a error occurs beforehand.

**Comment by paulpflug** [comment]
close due to inactivity - Please let me know if you have further problems
